In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
from sklearn.decomposition import PCA
from sklearn import datasets

In [3]:
dataset = datasets.load_iris()

In [4]:
X = dataset['data']
y = dataset['target']

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 64)

In [6]:
pca = PCA(n_components=3)
#we are reducing from 4 features to 3

In [7]:
X_train

array([[5.7, 2.8, 4.1, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5.5, 2.3, 4. , 1.3],
       [5. , 3.3, 1.4, 0.2],
       [6. , 2.9, 4.5, 1.5],
       [6.5, 3. , 5.2, 2. ],
       [4.6, 3.1, 1.5, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [4.6, 3.6, 1. , 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5.6, 2.9, 3.6, 1.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.6, 4. , 1.2],
       [6.3, 2.3, 4.4, 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.8, 2.8, 5.1, 2.4],
       [5.5, 2.4, 3.7, 1. ],
       [5.7, 2.9, 4.2, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 2.5, 5.8, 1.8],
       [7.7, 2.8, 6.7, 2. ],
       [6.1, 2.8, 4.7, 1.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3

In [8]:
X_train = pca.fit_transform(X_train)

In [9]:
X_train

array([[ 0.31484141, -0.33884266,  0.03876432],
       [-0.7359588 , -0.99066939,  0.06263748],
       [-2.82323511, -0.20255152,  0.1008245 ],
       [ 1.13231242, -0.060259  ,  0.47935433],
       [ 0.19741245, -0.82734759, -0.13910201],
       [-2.68556847,  0.1235874 , -0.08920642],
       [ 0.82979244, -0.15501106,  0.05631813],
       [ 1.78139009,  0.08334805,  0.13589831],
       [-2.72935373, -0.29486484,  0.05325921],
       [ 1.11316241,  0.2965641 ,  0.17590564],
       [ 1.79750808, -0.49311426, -0.11422868],
       [ 0.73322858,  0.14221671, -0.31609148],
       [-3.19876066,  0.16670178,  0.29108565],
       [ 1.31474329, -0.33662591, -0.32016354],
       [-0.15810553, -0.24363949,  0.10561185],
       [ 0.96037906, -0.56159906, -0.47567061],
       [-2.48695554,  0.6612303 , -0.09375021],
       [ 1.91707848,  0.14532114,  0.73064681],
       [ 0.52814073, -0.09252589,  0.14456129],
       [ 2.9360643 ,  0.79385311,  0.40404264],
       [ 0.24655192, -0.40468357, -0.201

In [10]:
pca.components_

array([[ 0.36475104, -0.08233773,  0.85647613,  0.35584522],
       [ 0.62546148,  0.75954328, -0.16358997, -0.07162595],
       [-0.62073505,  0.58263104,  0.10697816,  0.51359978]])

In [11]:
pca.explained_variance_ratio_

array([0.92439022, 0.05464073, 0.01593832])